language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script:
  - phpunit --coverage-clover=coverage.xml
  - php codecov.php coverage.xml 1

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - wget http://get.sensiolabs.org/sami.phar
  - php sami.phar update sami-config.php --force
deploy:
  provider: surge
  skip_cleanup: true
  project: ./build/
  domain: cloudflare-graphql.surge.sh
  on:
    php: '7.3'

#
