name: ApiGen

on: [push]

jobs:
  apigen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: ApiGen Docs Generator
      uses: wappr/action-apigen@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
